/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Facturitas;


import javax.swing.JOptionPane;
import productosDAL.conexion;

/**
 *
 * @author HOME
 */
public class frmFacturas extends javax.swing.JFrame {

    /**
     * Creates new form frmFacturas
     */
    public frmFacturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precioFinalTxt3 = new javax.swing.JTextField();
        CANTIDADTXT2 = new javax.swing.JTextField();
        CANTIDADTXT3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Subtotaltxt = new javax.swing.JTextField();
        IVAtxt = new javax.swing.JTextField();
        TotalTxt = new javax.swing.JTextField();
        EjecutarBT = new javax.swing.JButton();
        Producostxt = new javax.swing.JTextField();
        Preciotxt = new javax.swing.JTextField();
        precioFinalTxt = new javax.swing.JTextField();
        Producostxt1 = new javax.swing.JTextField();
        Preciotxt1 = new javax.swing.JTextField();
        precioFinalTxt1 = new javax.swing.JTextField();
        CANTIDADTXT1 = new javax.swing.JTextField();
        Producostxt2 = new javax.swing.JTextField();
        Preciotxt2 = new javax.swing.JTextField();
        precioFinalTxt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CANTIDADTXT = new javax.swing.JTextField();
        Producostxt3 = new javax.swing.JTextField();
        Preciotxt3 = new javax.swing.JTextField();
        BORRAR2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        precioFinalTxt3.setEditable(false);
        precioFinalTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioFinalTxt3ActionPerformed(evt);
            }
        });

        CANTIDADTXT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTIDADTXT2ActionPerformed(evt);
            }
        });

        CANTIDADTXT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTIDADTXT3ActionPerformed(evt);
            }
        });

        jLabel7.setText("SUBTOTAL");

        jLabel8.setText("IVA");

        jLabel9.setText("TOTAL");

        Subtotaltxt.setEditable(false);

        IVAtxt.setEditable(false);

        TotalTxt.setEditable(false);

        EjecutarBT.setText("Ejecutar");
        EjecutarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarBTActionPerformed(evt);
            }
        });

        Producostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducostxtActionPerformed(evt);
            }
        });

        Preciotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreciotxtActionPerformed(evt);
            }
        });

        precioFinalTxt.setEditable(false);
        precioFinalTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precioFinalTxtMouseClicked(evt);
            }
        });

        Producostxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Producostxt1ActionPerformed(evt);
            }
        });

        Preciotxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preciotxt1ActionPerformed(evt);
            }
        });

        precioFinalTxt1.setEditable(false);
        precioFinalTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioFinalTxt1ActionPerformed(evt);
            }
        });

        CANTIDADTXT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTIDADTXT1ActionPerformed(evt);
            }
        });

        Producostxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Producostxt2ActionPerformed(evt);
            }
        });

        Preciotxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preciotxt2ActionPerformed(evt);
            }
        });

        precioFinalTxt2.setEditable(false);

        jLabel1.setText("FACTURA FARMACIA ");

        jLabel3.setText("CANTIDAD");

        jLabel4.setText("PRODUCTOS");

        jLabel5.setText("PRECIO");

        jLabel6.setText("PRECIO TOTAL");

        CANTIDADTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTIDADTXTActionPerformed(evt);
            }
        });

        Producostxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Producostxt3ActionPerformed(evt);
            }
        });

        Preciotxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preciotxt3ActionPerformed(evt);
            }
        });

        BORRAR2.setText("LIMPIAR");
        BORRAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRAR2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(127, 127, 127)
                                .addComponent(jLabel4)))
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CANTIDADTXT2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(CANTIDADTXT1)
                                .addComponent(CANTIDADTXT))
                            .addComponent(CANTIDADTXT3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Producostxt, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(Producostxt1)
                            .addComponent(Producostxt2)
                            .addComponent(Producostxt3))
                        .addGap(60, 60, 60)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Preciotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addComponent(Preciotxt1))
                            .addComponent(Preciotxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Preciotxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(precioFinalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(precioFinalTxt1)
                            .addComponent(precioFinalTxt2)
                            .addComponent(precioFinalTxt3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EjecutarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BORRAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IVAtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Subtotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CANTIDADTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Producostxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Preciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioFinalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CANTIDADTXT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Producostxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Preciotxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioFinalTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Producostxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioFinalTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CANTIDADTXT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Preciotxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Producostxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioFinalTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CANTIDADTXT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Preciotxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Subtotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IVAtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EjecutarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(BORRAR2))
                .addGap(147, 147, 147))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precioFinalTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioFinalTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioFinalTxt3ActionPerformed

    private void CANTIDADTXT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTIDADTXT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANTIDADTXT2ActionPerformed

    private void CANTIDADTXT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTIDADTXT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANTIDADTXT3ActionPerformed

    private void EjecutarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarBTActionPerformed
        // TODO add your handling code here:
       /* conexion Objconecion=new conexion();
        VARIABLES oProductos= recuperarDatosGUI();
        
        
        String strSentenciaInsert = String.format("UPDATE Productos SET Stock='%s'", oProductos.getCantidad(),oProductos.getCantidad1(),oProductos.getCantidad2(),oProductos.getCantidad3());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);*/
        
      
       if(Producostxt.getText().isEmpty()||Producostxt1.getText().isEmpty()||Producostxt2.getText().isEmpty()||Producostxt3.getText().isEmpty()){
           JOptionPane.showInternalMessageDialog(null, "LLene todos  los campos o datos no registrados en la base de datos");
       }
       else if(CANTIDADTXT.getText().isEmpty()||CANTIDADTXT1.getText().isEmpty()||CANTIDADTXT2.getText().isEmpty()||CANTIDADTXT3.getText().isEmpty()){
           JOptionPane.showInternalMessageDialog(null, "LLene todos  los campos o datos no registrados en la base de datos");
       }
       else if(Preciotxt.getText().isEmpty()||Preciotxt1.getText().isEmpty()||Preciotxt2.getText().isEmpty()||Preciotxt3.getText().isEmpty()){
           JOptionPane.showInternalMessageDialog(null, "LLene todos  los campos o datos no registrados en la base de datos");
       }
       else{
        double subtotal,total,pr,cany,total0,pr0,cany0,total11,pr1,cany1,total12,pr2,cany2,ivaa,sumatotal;
        pr=Double.parseDouble(Preciotxt.getText());
        cany=Double.parseDouble(CANTIDADTXT.getText());
        total=pr*cany;
        String totall=total+ "";
        precioFinalTxt.setText(totall);
        
        pr0=Double.parseDouble(Preciotxt1.getText());
        cany0=Double.parseDouble(CANTIDADTXT1.getText());
        total0=pr0*cany0;
        String totala=total0+ "";
        precioFinalTxt1.setText(totala);
        
        pr1=Double.parseDouble(Preciotxt2.getText());
        cany1=Double.parseDouble(CANTIDADTXT2.getText());
        total11=pr1*cany1;
        String totalb=total11+ "";
        precioFinalTxt2.setText(totalb);
        
        pr2=Double.parseDouble(Preciotxt3.getText());
        cany2=Double.parseDouble(CANTIDADTXT3.getText());
        total12=pr2*cany2;
        String totalc=total12+ "";
        precioFinalTxt3.setText(totalc);
        
        subtotal=total+total0+total11+total12;
        String toalSub=subtotal+"";
        Subtotaltxt.setText(toalSub);
        
        ivaa=subtotal*0.12;
        String ivas=ivaa+"";
        IVAtxt.setText(ivas);
        
        sumatotal=ivaa+subtotal;
        String suma=sumatotal+"";
        TotalTxt.setText(suma);
       }
        
    }//GEN-LAST:event_EjecutarBTActionPerformed

    private void ProducostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducostxtActionPerformed

    private void PreciotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreciotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreciotxtActionPerformed

    private void Producostxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producostxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Producostxt1ActionPerformed

    private void Preciotxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preciotxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preciotxt1ActionPerformed

    private void precioFinalTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioFinalTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioFinalTxt1ActionPerformed

    private void CANTIDADTXT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTIDADTXT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANTIDADTXT1ActionPerformed

    private void Producostxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producostxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Producostxt2ActionPerformed

    private void Preciotxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preciotxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preciotxt2ActionPerformed

    private void CANTIDADTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTIDADTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANTIDADTXTActionPerformed

    private void Producostxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producostxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Producostxt3ActionPerformed

    private void Preciotxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preciotxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preciotxt3ActionPerformed

    private void BORRAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRAR2ActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_BORRAR2ActionPerformed

    private void precioFinalTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioFinalTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_precioFinalTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BORRAR2;
    private javax.swing.JTextField CANTIDADTXT;
    private javax.swing.JTextField CANTIDADTXT1;
    private javax.swing.JTextField CANTIDADTXT2;
    private javax.swing.JTextField CANTIDADTXT3;
    private javax.swing.JButton EjecutarBT;
    private javax.swing.JTextField IVAtxt;
    private javax.swing.JTextField Preciotxt;
    private javax.swing.JTextField Preciotxt1;
    private javax.swing.JTextField Preciotxt2;
    private javax.swing.JTextField Preciotxt3;
    private javax.swing.JTextField Producostxt;
    private javax.swing.JTextField Producostxt1;
    private javax.swing.JTextField Producostxt2;
    private javax.swing.JTextField Producostxt3;
    private javax.swing.JTextField Subtotaltxt;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField precioFinalTxt;
    private javax.swing.JTextField precioFinalTxt1;
    private javax.swing.JTextField precioFinalTxt2;
    private javax.swing.JTextField precioFinalTxt3;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
    CANTIDADTXT.setText("");
    CANTIDADTXT1.setText("");
    CANTIDADTXT2.setText("");
    CANTIDADTXT3.setText("");
    Producostxt.setText("");
    Producostxt1.setText("");
    Producostxt2.setText("");
    Producostxt3.setText("");
    Preciotxt1.setText("");
    Preciotxt2.setText("");
    Preciotxt3.setText("");
    Preciotxt.setText("");
    precioFinalTxt.setText("");
    precioFinalTxt1.setText("");
    precioFinalTxt2.setText("");
    precioFinalTxt3.setText("");
    Subtotaltxt.setText("");
    IVAtxt.setText("");
    TotalTxt.setText("") ;
    }

    private VARIABLES recuperarDatosGUI() {
       VARIABLES oEmpleados =new VARIABLES();

        oEmpleados.setCantidad(CANTIDADTXT.getText());
        oEmpleados.setCantidad1(CANTIDADTXT1.getText());
        oEmpleados.setCantidad2(CANTIDADTXT2.getText());
        oEmpleados.setCantidad3(CANTIDADTXT3.getText());
        
        oEmpleados.setNombre(Producostxt.getText());
        oEmpleados.setNombre1(Producostxt1.getText());
        oEmpleados.setNombre2(Producostxt2.getText());
        oEmpleados.setNombre3(Producostxt3.getText());
        
        oEmpleados.setPrecio(Preciotxt.getText());
        oEmpleados.setPrecio1(Preciotxt1.getText());
        oEmpleados.setPrecio2(Preciotxt2.getText());
        oEmpleados.setPrecio3(Preciotxt3.getText());
        return oEmpleados; }
}
