/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Facturitas;


import InicioGUI.frmInicio;
import javax.swing.JOptionPane;
import productosDAL.conexion;

/**
 *
 * @author HOME
 */
public class frmFacturas extends javax.swing.JFrame {

    /**
     * Creates new form frmFacturas
     */
    public frmFacturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precioFinalTxt3 = new javax.swing.JTextField();
        CANTIDADTXT2 = new javax.swing.JTextField();
        CANTIDADTXT3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Subtotaltxt = new javax.swing.JTextField();
        IVAtxt = new javax.swing.JTextField();
        TotalTxt = new javax.swing.JTextField();
        EjecutarBT = new javax.swing.JButton();
        Producostxt = new javax.swing.JTextField();
        Preciotxt = new javax.swing.JTextField();
        precioFinalTxt = new javax.swing.JTextField();
        Producostxt1 = new javax.swing.JTextField();
        Preciotxt1 = new javax.swing.JTextField();
        precioFinalTxt1 = new javax.swing.JTextField();
        CANTIDADTXT1 = new javax.swing.JTextField();
        Producostxt2 = new javax.swing.JTextField();
        Preciotxt2 = new javax.swing.JTextField();
        precioFinalTxt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CANTIDADTXT = new javax.swing.JTextField();
        Producostxt3 = new javax.swing.JTextField();
        Preciotxt3 = new javax.swing.JTextField();
        BORRAR2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        precioFinalTxt3.setEditable(false);
        precioFinalTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioFinalTxt3ActionPerformed(evt);
            }
        });
        getContentPane().add(precioFinalTxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 286, 78, -1));

        CANTIDADTXT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTIDADTXT2ActionPerformed(evt);
            }
        });
        getContentPane().add(CANTIDADTXT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 252, 104, -1));

        CANTIDADTXT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTIDADTXT3ActionPerformed(evt);
            }
        });
        getContentPane().add(CANTIDADTXT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 286, 104, -1));

        jLabel7.setText("SUBTOTAL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 329, -1, -1));

        jLabel8.setText("IVA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 369, -1, -1));

        jLabel9.setText("TOTAL");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 409, -1, -1));

        Subtotaltxt.setEditable(false);
        getContentPane().add(Subtotaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 326, 124, -1));

        IVAtxt.setEditable(false);
        getContentPane().add(IVAtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 366, 124, -1));

        TotalTxt.setEditable(false);
        getContentPane().add(TotalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 406, 124, -1));

        EjecutarBT.setText("Ejecutar");
        EjecutarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarBTActionPerformed(evt);
            }
        });
        getContentPane().add(EjecutarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 353, 92, 35));

        Producostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProducostxtActionPerformed(evt);
            }
        });
        getContentPane().add(Producostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 178, 183, -1));

        Preciotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreciotxtActionPerformed(evt);
            }
        });
        getContentPane().add(Preciotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 178, 84, -1));

        precioFinalTxt.setEditable(false);
        precioFinalTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precioFinalTxtMouseClicked(evt);
            }
        });
        getContentPane().add(precioFinalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 178, 78, -1));

        Producostxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Producostxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(Producostxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 212, 183, -1));

        Preciotxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preciotxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(Preciotxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 212, 84, -1));

        precioFinalTxt1.setEditable(false);
        precioFinalTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioFinalTxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(precioFinalTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 212, 78, -1));

        CANTIDADTXT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTIDADTXT1ActionPerformed(evt);
            }
        });
        getContentPane().add(CANTIDADTXT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 212, 104, -1));

        Producostxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Producostxt2ActionPerformed(evt);
            }
        });
        getContentPane().add(Producostxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 252, 183, -1));

        Preciotxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preciotxt2ActionPerformed(evt);
            }
        });
        getContentPane().add(Preciotxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 252, 84, -1));

        precioFinalTxt2.setEditable(false);
        getContentPane().add(precioFinalTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 252, 78, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("FACTURA FARMACIA ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 390, 70));

        jLabel3.setText("CANTIDAD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 144, -1, -1));

        jLabel4.setText("PRODUCTOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 144, -1, -1));

        jLabel5.setText("PRECIO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 144, -1, -1));

        jLabel6.setText("PRECIO TOTAL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 144, -1, -1));

        CANTIDADTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANTIDADTXTActionPerformed(evt);
            }
        });
        getContentPane().add(CANTIDADTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 178, 104, -1));

        Producostxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Producostxt3ActionPerformed(evt);
            }
        });
        getContentPane().add(Producostxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 286, 183, -1));

        Preciotxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preciotxt3ActionPerformed(evt);
            }
        });
        getContentPane().add(Preciotxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 286, 84, -1));

        BORRAR2.setText("LIMPIAR");
        BORRAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRAR2ActionPerformed(evt);
            }
        });
        getContentPane().add(BORRAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 406, 94, -1));

        jButton1.setText("regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 36, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/farmacia.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 840, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precioFinalTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioFinalTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioFinalTxt3ActionPerformed

    private void CANTIDADTXT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTIDADTXT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANTIDADTXT2ActionPerformed

    private void CANTIDADTXT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTIDADTXT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANTIDADTXT3ActionPerformed

    private void EjecutarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarBTActionPerformed
        // TODO add your handling code here:
       /* conexion Objconecion=new conexion();
        VARIABLES oProductos= recuperarDatosGUI();
        
        
        String strSentenciaInsert = String.format("UPDATE Productos SET Stock='%s'", oProductos.getCantidad(),oProductos.getCantidad1(),oProductos.getCantidad2(),oProductos.getCantidad3());
        
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);*/
        
      
       if(Producostxt.getText().isEmpty()||Producostxt1.getText().isEmpty()||Producostxt2.getText().isEmpty()||Producostxt3.getText().isEmpty()){
           JOptionPane.showInternalMessageDialog(null, "LLene todos  los campos o datos no registrados en la base de datos");
       }
       else if(CANTIDADTXT.getText().isEmpty()||CANTIDADTXT1.getText().isEmpty()||CANTIDADTXT2.getText().isEmpty()||CANTIDADTXT3.getText().isEmpty()){
           JOptionPane.showInternalMessageDialog(null, "LLene todos  los campos o datos no registrados en la base de datos");
       }
       else if(Preciotxt.getText().isEmpty()||Preciotxt1.getText().isEmpty()||Preciotxt2.getText().isEmpty()||Preciotxt3.getText().isEmpty()){
           JOptionPane.showInternalMessageDialog(null, "LLene todos  los campos o datos no registrados en la base de datos");
       }
       else{
        double subtotal,total,pr,cany,total0,pr0,cany0,total11,pr1,cany1,total12,pr2,cany2,ivaa,sumatotal;
        pr=Double.parseDouble(Preciotxt.getText());
        cany=Double.parseDouble(CANTIDADTXT.getText());
        total=pr*cany;
        String totall=total+ "";
        precioFinalTxt.setText(totall);
        
        pr0=Double.parseDouble(Preciotxt1.getText());
        cany0=Double.parseDouble(CANTIDADTXT1.getText());
        total0=pr0*cany0;
        String totala=total0+ "";
        precioFinalTxt1.setText(totala);
        
        pr1=Double.parseDouble(Preciotxt2.getText());
        cany1=Double.parseDouble(CANTIDADTXT2.getText());
        total11=pr1*cany1;
        String totalb=total11+ "";
        precioFinalTxt2.setText(totalb);
        
        pr2=Double.parseDouble(Preciotxt3.getText());
        cany2=Double.parseDouble(CANTIDADTXT3.getText());
        total12=pr2*cany2;
        String totalc=total12+ "";
        precioFinalTxt3.setText(totalc);
        
        subtotal=total+total0+total11+total12;
        String toalSub=subtotal+"";
        Subtotaltxt.setText(toalSub);
        
        ivaa=subtotal*0.12;
        String ivas=ivaa+"";
        IVAtxt.setText(ivas);
        
        sumatotal=ivaa+subtotal;
        String suma=sumatotal+"";
        TotalTxt.setText(suma);
       }
        
    }//GEN-LAST:event_EjecutarBTActionPerformed

    private void ProducostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProducostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProducostxtActionPerformed

    private void PreciotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreciotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreciotxtActionPerformed

    private void Producostxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producostxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Producostxt1ActionPerformed

    private void Preciotxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preciotxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preciotxt1ActionPerformed

    private void precioFinalTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioFinalTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioFinalTxt1ActionPerformed

    private void CANTIDADTXT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTIDADTXT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANTIDADTXT1ActionPerformed

    private void Producostxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producostxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Producostxt2ActionPerformed

    private void Preciotxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preciotxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preciotxt2ActionPerformed

    private void CANTIDADTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANTIDADTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANTIDADTXTActionPerformed

    private void Producostxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producostxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Producostxt3ActionPerformed

    private void Preciotxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preciotxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preciotxt3ActionPerformed

    private void BORRAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRAR2ActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_BORRAR2ActionPerformed

    private void precioFinalTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioFinalTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_precioFinalTxtMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        frmInicio Loguin=new frmInicio();
        Loguin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BORRAR2;
    private javax.swing.JTextField CANTIDADTXT;
    private javax.swing.JTextField CANTIDADTXT1;
    private javax.swing.JTextField CANTIDADTXT2;
    private javax.swing.JTextField CANTIDADTXT3;
    private javax.swing.JButton EjecutarBT;
    private javax.swing.JTextField IVAtxt;
    private javax.swing.JTextField Preciotxt;
    private javax.swing.JTextField Preciotxt1;
    private javax.swing.JTextField Preciotxt2;
    private javax.swing.JTextField Preciotxt3;
    private javax.swing.JTextField Producostxt;
    private javax.swing.JTextField Producostxt1;
    private javax.swing.JTextField Producostxt2;
    private javax.swing.JTextField Producostxt3;
    private javax.swing.JTextField Subtotaltxt;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField precioFinalTxt;
    private javax.swing.JTextField precioFinalTxt1;
    private javax.swing.JTextField precioFinalTxt2;
    private javax.swing.JTextField precioFinalTxt3;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
    CANTIDADTXT.setText("");
    CANTIDADTXT1.setText("");
    CANTIDADTXT2.setText("");
    CANTIDADTXT3.setText("");
    Producostxt.setText("");
    Producostxt1.setText("");
    Producostxt2.setText("");
    Producostxt3.setText("");
    Preciotxt1.setText("");
    Preciotxt2.setText("");
    Preciotxt3.setText("");
    Preciotxt.setText("");
    precioFinalTxt.setText("");
    precioFinalTxt1.setText("");
    precioFinalTxt2.setText("");
    precioFinalTxt3.setText("");
    Subtotaltxt.setText("");
    IVAtxt.setText("");
    TotalTxt.setText("") ;
    }

    private VARIABLES recuperarDatosGUI() {
       VARIABLES oEmpleados =new VARIABLES();

        oEmpleados.setCantidad(CANTIDADTXT.getText());
        oEmpleados.setCantidad1(CANTIDADTXT1.getText());
        oEmpleados.setCantidad2(CANTIDADTXT2.getText());
        oEmpleados.setCantidad3(CANTIDADTXT3.getText());
        
        oEmpleados.setNombre(Producostxt.getText());
        oEmpleados.setNombre1(Producostxt1.getText());
        oEmpleados.setNombre2(Producostxt2.getText());
        oEmpleados.setNombre3(Producostxt3.getText());
        
        oEmpleados.setPrecio(Preciotxt.getText());
        oEmpleados.setPrecio1(Preciotxt1.getText());
        oEmpleados.setPrecio2(Preciotxt2.getText());
        oEmpleados.setPrecio3(Preciotxt3.getText());
        return oEmpleados; }
}
